import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'es' | 'fr' | 'de' | 'zh' | 'ja' | 'hi' | 'ar' | 'pt' | 'ru' | 'ko' | 'tr' | 'it' | 'pl' | 'nl';

export interface Translations {
  // Navigation
  home: string;
  movies: string;
  tvShows: string;
  trending: string;
  watchlist: string;
  search: string;
  
  // Common
  signIn: string;
  signUp: string;
  signOut: string;
  profile: string;
  settings: string;
  watchHistory: string;
  
  // Actions
  watchNow: string;
  moreInfo: string;
  addToWatchlist: string;
  removeFromWatchlist: string;
  inWatchlist: string;
  back: string;
  save: string;
  cancel: string;
  edit: string;
  delete: string;
  clear: string;
  
  // Content
  popular: string;
  topRated: string;
  nowPlaying: string;
  upcoming: string;
  continueWatching: string;
  
  // Player
  areYouStillWatching: string;
  yesContinue: string;
  stopPlaying: string;
  skipIntro: string;
  skipOutro: string;
  
  // Settings
  appearance: string;
  playback: string;
  audioSubtitles: string;
  notifications: string;
  parentalControls: string;
  dataUsage: string;
  account: string;
  theme: string;
  dark: string;
  light: string;
  language: string;
  
  // Messages
  welcomeBack: string;
  startJourney: string;
  noResults: string;
  loading: string;
}

const translations: Record<Language, Translations> = {
  en: {
    home: 'Home',
    movies: 'Movies',
    tvShows: 'TV Shows',
    trending: 'Trending',
    watchlist: 'Watchlist',
    search: 'Search',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signOut: 'Sign Out',
    profile: 'Profile',
    settings: 'Settings',
    watchHistory: 'Watch History',
    watchNow: 'Watch Now',
    moreInfo: 'More Info',
    addToWatchlist: 'Add to Watchlist',
    removeFromWatchlist: 'Remove from Watchlist',
    inWatchlist: 'In Watchlist',
    back: 'Back',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    clear: 'Clear',
    popular: 'Popular',
    topRated: 'Top Rated',
    nowPlaying: 'Now Playing',
    upcoming: 'Upcoming',
    continueWatching: 'Continue Watching',
    areYouStillWatching: 'Are you still watching?',
    yesContinue: 'Yes, Continue',
    stopPlaying: 'Stop Playing',
    skipIntro: 'Skip Intro',
    skipOutro: 'Skip Outro',
    appearance: 'Appearance',
    playback: 'Playback',
    audioSubtitles: 'Audio & Subtitles',
    notifications: 'Notifications',
    parentalControls: 'Parental Controls',
    dataUsage: 'Data Usage',
    account: 'Account',
    theme: 'Theme',
    dark: 'Dark',
    light: 'Light',
    language: 'Language',
    welcomeBack: 'Welcome back to your movie universe',
    startJourney: 'Start your cinematic journey',
    noResults: 'No results found',
    loading: 'Loading...',
  },
  es: {
    home: 'Inicio',
    movies: 'Películas',
    tvShows: 'Series',
    trending: 'Tendencias',
    watchlist: 'Mi Lista',
    search: 'Buscar',
    signIn: 'Iniciar Sesión',
    signUp: 'Registrarse',
    signOut: 'Cerrar Sesión',
    profile: 'Perfil',
    settings: 'Configuración',
    watchHistory: 'Historial',
    watchNow: 'Ver Ahora',
    moreInfo: 'Más Info',
    addToWatchlist: 'Agregar a Mi Lista',
    removeFromWatchlist: 'Quitar de Mi Lista',
    inWatchlist: 'En Mi Lista',
    back: 'Volver',
    save: 'Guardar',
    cancel: 'Cancelar',
    edit: 'Editar',
    delete: 'Eliminar',
    clear: 'Limpiar',
    popular: 'Populares',
    topRated: 'Mejor Valoradas',
    nowPlaying: 'En Cartelera',
    upcoming: 'Próximamente',
    continueWatching: 'Continuar Viendo',
    areYouStillWatching: '¿Sigues viendo?',
    yesContinue: 'Sí, Continuar',
    stopPlaying: 'Detener',
    skipIntro: 'Saltar Intro',
    skipOutro: 'Saltar Final',
    appearance: 'Apariencia',
    playback: 'Reproducción',
    audioSubtitles: 'Audio y Subtítulos',
    notifications: 'Notificaciones',
    parentalControls: 'Control Parental',
    dataUsage: 'Uso de Datos',
    account: 'Cuenta',
    theme: 'Tema',
    dark: 'Oscuro',
    light: 'Claro',
    language: 'Idioma',
    welcomeBack: 'Bienvenido de vuelta a tu universo de películas',
    startJourney: 'Comienza tu viaje cinematográfico',
    noResults: 'No se encontraron resultados',
    loading: 'Cargando...',
  },
  fr: {
    home: 'Accueil',
    movies: 'Films',
    tvShows: 'Séries',
    trending: 'Tendances',
    watchlist: 'Ma Liste',
    search: 'Rechercher',
    signIn: 'Se Connecter',
    signUp: "S'inscrire",
    signOut: 'Se Déconnecter',
    profile: 'Profil',
    settings: 'Paramètres',
    watchHistory: 'Historique',
    watchNow: 'Regarder',
    moreInfo: "Plus d'Info",
    addToWatchlist: 'Ajouter à Ma Liste',
    removeFromWatchlist: 'Retirer de Ma Liste',
    inWatchlist: 'Dans Ma Liste',
    back: 'Retour',
    save: 'Enregistrer',
    cancel: 'Annuler',
    edit: 'Modifier',
    delete: 'Supprimer',
    clear: 'Effacer',
    popular: 'Populaires',
    topRated: 'Mieux Notés',
    nowPlaying: 'En Salle',
    upcoming: 'À Venir',
    continueWatching: 'Continuer à Regarder',
    areYouStillWatching: 'Regardez-vous toujours?',
    yesContinue: 'Oui, Continuer',
    stopPlaying: 'Arrêter',
    skipIntro: "Passer l'Intro",
    skipOutro: 'Passer la Fin',
    appearance: 'Apparence',
    playback: 'Lecture',
    audioSubtitles: 'Audio et Sous-titres',
    notifications: 'Notifications',
    parentalControls: 'Contrôle Parental',
    dataUsage: 'Utilisation des Données',
    account: 'Compte',
    theme: 'Thème',
    dark: 'Sombre',
    light: 'Clair',
    language: 'Langue',
    welcomeBack: 'Bienvenue dans votre univers cinématographique',
    startJourney: 'Commencez votre voyage cinématographique',
    noResults: 'Aucun résultat trouvé',
    loading: 'Chargement...',
  },
  de: {
    home: 'Startseite',
    movies: 'Filme',
    tvShows: 'Serien',
    trending: 'Angesagt',
    watchlist: 'Meine Liste',
    search: 'Suchen',
    signIn: 'Anmelden',
    signUp: 'Registrieren',
    signOut: 'Abmelden',
    profile: 'Profil',
    settings: 'Einstellungen',
    watchHistory: 'Verlauf',
    watchNow: 'Jetzt Ansehen',
    moreInfo: 'Mehr Infos',
    addToWatchlist: 'Zur Liste hinzufügen',
    removeFromWatchlist: 'Aus Liste entfernen',
    inWatchlist: 'In der Liste',
    back: 'Zurück',
    save: 'Speichern',
    cancel: 'Abbrechen',
    edit: 'Bearbeiten',
    delete: 'Löschen',
    clear: 'Leeren',
    popular: 'Beliebt',
    topRated: 'Am besten bewertet',
    nowPlaying: 'Im Kino',
    upcoming: 'Demnächst',
    continueWatching: 'Weiterschauen',
    areYouStillWatching: 'Schaust du noch?',
    yesContinue: 'Ja, Weiter',
    stopPlaying: 'Stopp',
    skipIntro: 'Intro überspringen',
    skipOutro: 'Outro überspringen',
    appearance: 'Erscheinungsbild',
    playback: 'Wiedergabe',
    audioSubtitles: 'Audio & Untertitel',
    notifications: 'Benachrichtigungen',
    parentalControls: 'Jugendschutz',
    dataUsage: 'Datennutzung',
    account: 'Konto',
    theme: 'Thema',
    dark: 'Dunkel',
    light: 'Hell',
    language: 'Sprache',
    welcomeBack: 'Willkommen zurück in deiner Filmwelt',
    startJourney: 'Beginne deine cineastische Reise',
    noResults: 'Keine Ergebnisse gefunden',
    loading: 'Laden...',
  },
  zh: {
    home: '首页',
    movies: '电影',
    tvShows: '电视剧',
    trending: '热门',
    watchlist: '我的列表',
    search: '搜索',
    signIn: '登录',
    signUp: '注册',
    signOut: '退出',
    profile: '个人资料',
    settings: '设置',
    watchHistory: '观看历史',
    watchNow: '立即观看',
    moreInfo: '更多信息',
    addToWatchlist: '添加到列表',
    removeFromWatchlist: '从列表移除',
    inWatchlist: '在列表中',
    back: '返回',
    save: '保存',
    cancel: '取消',
    edit: '编辑',
    delete: '删除',
    clear: '清除',
    popular: '热门',
    topRated: '评分最高',
    nowPlaying: '正在上映',
    upcoming: '即将上映',
    continueWatching: '继续观看',
    areYouStillWatching: '你还在观看吗?',
    yesContinue: '是的,继续',
    stopPlaying: '停止播放',
    skipIntro: '跳过片头',
    skipOutro: '跳过片尾',
    appearance: '外观',
    playback: '播放',
    audioSubtitles: '音频和字幕',
    notifications: '通知',
    parentalControls: '家长控制',
    dataUsage: '数据使用',
    account: '账户',
    theme: '主题',
    dark: '深色',
    light: '浅色',
    language: '语言',
    welcomeBack: '欢迎回到你的电影世界',
    startJourney: '开始你的电影之旅',
    noResults: '未找到结果',
    loading: '加载中...',
  },
  ja: {
    home: 'ホーム',
    movies: '映画',
    tvShows: 'テレビ番組',
    trending: 'トレンド',
    watchlist: 'マイリスト',
    search: '検索',
    signIn: 'ログイン',
    signUp: '登録',
    signOut: 'ログアウト',
    profile: 'プロフィール',
    settings: '設定',
    watchHistory: '視聴履歴',
    watchNow: '今すぐ見る',
    moreInfo: '詳細',
    addToWatchlist: 'リストに追加',
    removeFromWatchlist: 'リストから削除',
    inWatchlist: 'リストに追加済み',
    back: '戻る',
    save: '保存',
    cancel: 'キャンセル',
    edit: '編集',
    delete: '削除',
    clear: 'クリア',
    popular: '人気',
    topRated: '高評価',
    nowPlaying: '上映中',
    upcoming: '公開予定',
    continueWatching: '視聴を続ける',
    areYouStillWatching: 'まだ見ていますか?',
    yesContinue: 'はい、続ける',
    stopPlaying: '停止',
    skipIntro: 'イントロをスキップ',
    skipOutro: 'アウトロをスキップ',
    appearance: '外観',
    playback: '再生',
    audioSubtitles: '音声と字幕',
    notifications: '通知',
    parentalControls: 'ペアレンタルコントロール',
    dataUsage: 'データ使用',
    account: 'アカウント',
    theme: 'テーマ',
    dark: 'ダーク',
    light: 'ライト',
    language: '言語',
    welcomeBack: '映画の世界へようこそ',
    startJourney: '映画の旅を始めよう',
    noResults: '結果が見つかりません',
    loading: '読み込み中...',
  },
  hi: {
    home: 'होम',
    movies: 'फिल्में',
    tvShows: 'टीवी शो',
    trending: 'ट्रेंडिंग',
    watchlist: 'मेरी सूची',
    search: 'खोजें',
    signIn: 'साइन इन',
    signUp: 'साइन अप',
    signOut: 'साइन आउट',
    profile: 'प्रोफाइल',
    settings: 'सेटिंग्स',
    watchHistory: 'देखने का इतिहास',
    watchNow: 'अभी देखें',
    moreInfo: 'अधिक जानकारी',
    addToWatchlist: 'सूची में जोड़ें',
    removeFromWatchlist: 'सूची से हटाएं',
    inWatchlist: 'सूची में है',
    back: 'वापस',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    clear: 'साफ करें',
    popular: 'लोकप्रिय',
    topRated: 'शीर्ष रेटेड',
    nowPlaying: 'अभी चल रही है',
    upcoming: 'आगामी',
    continueWatching: 'देखना जारी रखें',
    areYouStillWatching: 'क्या आप अभी भी देख रहे हैं?',
    yesContinue: 'हां, जारी रखें',
    stopPlaying: 'रोकें',
    skipIntro: 'इंट्रो छोड़ें',
    skipOutro: 'आउट्रो छोड़ें',
    appearance: 'रूप',
    playback: 'प्लेबैक',
    audioSubtitles: 'ऑडियो और सबटाइटल',
    notifications: 'सूचनाएं',
    parentalControls: 'पैरेंटल कंट्रोल',
    dataUsage: 'डेटा उपयोग',
    account: 'खाता',
    theme: 'थीम',
    dark: 'डार्क',
    light: 'लाइट',
    language: 'भाषा',
    welcomeBack: 'अपने फिल्म ब्रह्मांड में आपका स्वागत है',
    startJourney: 'अपनी सिनेमाई यात्रा शुरू करें',
    noResults: 'कोई परिणाम नहीं मिला',
    loading: 'लोड हो रहा है...',
  },
  ar: {
    home: 'الرئيسية',
    movies: 'أفلام',
    tvShows: 'مسلسلات',
    trending: 'رائج',
    watchlist: 'قائمتي',
    search: 'بحث',
    signIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    signOut: 'تسجيل الخروج',
    profile: 'الملف الشخصي',
    settings: 'الإعدادات',
    watchHistory: 'سجل المشاهدة',
    watchNow: 'شاهد الآن',
    moreInfo: 'مزيد من المعلومات',
    addToWatchlist: 'أضف إلى القائمة',
    removeFromWatchlist: 'إزالة من القائمة',
    inWatchlist: 'في القائمة',
    back: 'رجوع',
    save: 'حفظ',
    cancel: 'إلغاء',
    edit: 'تعديل',
    delete: 'حذف',
    clear: 'مسح',
    popular: 'شائع',
    topRated: 'الأعلى تقييماً',
    nowPlaying: 'يعرض الآن',
    upcoming: 'قادم',
    continueWatching: 'متابعة المشاهدة',
    areYouStillWatching: 'هل ما زلت تشاهد؟',
    yesContinue: 'نعم، تابع',
    stopPlaying: 'إيقاف',
    skipIntro: 'تخطي المقدمة',
    skipOutro: 'تخطي الخاتمة',
    appearance: 'المظهر',
    playback: 'التشغيل',
    audioSubtitles: 'الصوت والترجمات',
    notifications: 'الإشعارات',
    parentalControls: 'الرقابة الأبوية',
    dataUsage: 'استخدام البيانات',
    account: 'الحساب',
    theme: 'السمة',
    dark: 'داكن',
    light: 'فاتح',
    language: 'اللغة',
    welcomeBack: 'مرحباً بعودتك إلى عالم الأفلام',
    startJourney: 'ابدأ رحلتك السينمائية',
    noResults: 'لم يتم العثور على نتائج',
    loading: 'جاري التحميل...',
  },
  pt: {
    home: 'Início',
    movies: 'Filmes',
    tvShows: 'Séries',
    trending: 'Em Alta',
    watchlist: 'Minha Lista',
    search: 'Buscar',
    signIn: 'Entrar',
    signUp: 'Cadastrar',
    signOut: 'Sair',
    profile: 'Perfil',
    settings: 'Configurações',
    watchHistory: 'Histórico',
    watchNow: 'Assistir Agora',
    moreInfo: 'Mais Info',
    addToWatchlist: 'Adicionar à Lista',
    removeFromWatchlist: 'Remover da Lista',
    inWatchlist: 'Na Lista',
    back: 'Voltar',
    save: 'Salvar',
    cancel: 'Cancelar',
    edit: 'Editar',
    delete: 'Excluir',
    clear: 'Limpar',
    popular: 'Populares',
    topRated: 'Mais Bem Avaliados',
    nowPlaying: 'Em Cartaz',
    upcoming: 'Em Breve',
    continueWatching: 'Continuar Assistindo',
    areYouStillWatching: 'Você ainda está assistindo?',
    yesContinue: 'Sim, Continuar',
    stopPlaying: 'Parar',
    skipIntro: 'Pular Introdução',
    skipOutro: 'Pular Final',
    appearance: 'Aparência',
    playback: 'Reprodução',
    audioSubtitles: 'Áudio e Legendas',
    notifications: 'Notificações',
    parentalControls: 'Controle Parental',
    dataUsage: 'Uso de Dados',
    account: 'Conta',
    theme: 'Tema',
    dark: 'Escuro',
    light: 'Claro',
    language: 'Idioma',
    welcomeBack: 'Bem-vindo de volta ao seu universo de filmes',
    startJourney: 'Comece sua jornada cinematográfica',
    noResults: 'Nenhum resultado encontrado',
    loading: 'Carregando...',
  },
  ru: {
    home: 'Главная',
    movies: 'Фильмы',
    tvShows: 'Сериалы',
    trending: 'Популярное',
    watchlist: 'Мой список',
    search: 'Поиск',
    signIn: 'Войти',
    signUp: 'Регистрация',
    signOut: 'Выйти',
    profile: 'Профиль',
    settings: 'Настройки',
    watchHistory: 'История просмотров',
    watchNow: 'Смотреть',
    moreInfo: 'Подробнее',
    addToWatchlist: 'Добавить в список',
    removeFromWatchlist: 'Удалить из списка',
    inWatchlist: 'В списке',
    back: 'Назад',
    save: 'Сохранить',
    cancel: 'Отмена',
    edit: 'Редактировать',
    delete: 'Удалить',
    clear: 'Очистить',
    popular: 'Популярные',
    topRated: 'Лучшие',
    nowPlaying: 'Сейчас в кино',
    upcoming: 'Скоро',
    continueWatching: 'Продолжить просмотр',
    areYouStillWatching: 'Вы всё ещё смотрите?',
    yesContinue: 'Да, продолжить',
    stopPlaying: 'Остановить',
    skipIntro: 'Пропустить заставку',
    skipOutro: 'Пропустить концовку',
    appearance: 'Внешний вид',
    playback: 'Воспроизведение',
    audioSubtitles: 'Аудио и субтитры',
    notifications: 'Уведомления',
    parentalControls: 'Родительский контроль',
    dataUsage: 'Использование данных',
    account: 'Аккаунт',
    theme: 'Тема',
    dark: 'Тёмная',
    light: 'Светлая',
    language: 'Язык',
    welcomeBack: 'Добро пожаловать в ваш мир кино',
    startJourney: 'Начните своё кинематографическое путешествие',
    noResults: 'Ничего не найдено',
    loading: 'Загрузка...',
  },
  ko: {
    home: '홈',
    movies: '영화',
    tvShows: 'TV 프로그램',
    trending: '인기',
    watchlist: '내가 찜한 콘텐츠',
    search: '검색',
    signIn: '로그인',
    signUp: '회원가입',
    signOut: '로그아웃',
    profile: '프로필',
    settings: '설정',
    watchHistory: '시청 기록',
    watchNow: '지금 시청',
    moreInfo: '상세 정보',
    addToWatchlist: '찜한 콘텐츠에 추가',
    removeFromWatchlist: '찜한 콘텐츠에서 제거',
    inWatchlist: '찜한 콘텐츠에 있음',
    back: '뒤로',
    save: '저장',
    cancel: '취소',
    edit: '편집',
    delete: '삭제',
    clear: '지우기',
    popular: '인기 작품',
    topRated: '평점 높은 작품',
    nowPlaying: '상영중',
    upcoming: '개봉 예정',
    continueWatching: '시청 계속하기',
    areYouStillWatching: '계속 시청하시겠습니까?',
    yesContinue: '예, 계속',
    stopPlaying: '중지',
    skipIntro: '오프닝 건너뛰기',
    skipOutro: '엔딩 건너뛰기',
    appearance: '외관',
    playback: '재생',
    audioSubtitles: '오디오 및 자막',
    notifications: '알림',
    parentalControls: '자녀 보호',
    dataUsage: '데이터 사용',
    account: '계정',
    theme: '테마',
    dark: '다크',
    light: '라이트',
    language: '언어',
    welcomeBack: '영화의 세계에 다시 오신 것을 환영합니다',
    startJourney: '영화 여행을 시작하세요',
    noResults: '결과를 찾을 수 없습니다',
    loading: '로딩 중...',
  },
  tr: {
    home: 'Ana Sayfa',
    movies: 'Filmler',
    tvShows: 'Diziler',
    trending: 'Trend',
    watchlist: 'Listem',
    search: 'Ara',
    signIn: 'Giriş Yap',
    signUp: 'Kayıt Ol',
    signOut: 'Çıkış Yap',
    profile: 'Profil',
    settings: 'Ayarlar',
    watchHistory: 'İzleme Geçmişi',
    watchNow: 'Şimdi İzle',
    moreInfo: 'Daha Fazla Bilgi',
    addToWatchlist: 'Listeye Ekle',
    removeFromWatchlist: 'Listeden Kaldır',
    inWatchlist: 'Listede',
    back: 'Geri',
    save: 'Kaydet',
    cancel: 'İptal',
    edit: 'Düzenle',
    delete: 'Sil',
    clear: 'Temizle',
    popular: 'Popüler',
    topRated: 'En Yüksek Puanlı',
    nowPlaying: 'Vizyonda',
    upcoming: 'Yakında',
    continueWatching: 'İzlemeye Devam Et',
    areYouStillWatching: 'Hâlâ izliyor musunuz?',
    yesContinue: 'Evet, Devam Et',
    stopPlaying: 'Durdur',
    skipIntro: 'Jeneriği Atla',
    skipOutro: 'Kapanışı Atla',
    appearance: 'Görünüm',
    playback: 'Oynatma',
    audioSubtitles: 'Ses ve Altyazı',
    notifications: 'Bildirimler',
    parentalControls: 'Ebeveyn Kontrolü',
    dataUsage: 'Veri Kullanımı',
    account: 'Hesap',
    theme: 'Tema',
    dark: 'Koyu',
    light: 'Açık',
    language: 'Dil',
    welcomeBack: 'Film evreninize tekrar hoş geldiniz',
    startJourney: 'Sinema yolculuğunuza başlayın',
    noResults: 'Sonuç bulunamadı',
    loading: 'Yükleniyor...',
  },
  it: {
    home: 'Home',
    movies: 'Film',
    tvShows: 'Serie TV',
    trending: 'Di Tendenza',
    watchlist: 'La Mia Lista',
    search: 'Cerca',
    signIn: 'Accedi',
    signUp: 'Registrati',
    signOut: 'Esci',
    profile: 'Profilo',
    settings: 'Impostazioni',
    watchHistory: 'Cronologia',
    watchNow: 'Guarda Ora',
    moreInfo: 'Più Info',
    addToWatchlist: 'Aggiungi alla Lista',
    removeFromWatchlist: 'Rimuovi dalla Lista',
    inWatchlist: 'Nella Lista',
    back: 'Indietro',
    save: 'Salva',
    cancel: 'Annulla',
    edit: 'Modifica',
    delete: 'Elimina',
    clear: 'Cancella',
    popular: 'Popolari',
    topRated: 'Più Votati',
    nowPlaying: 'Al Cinema',
    upcoming: 'In Arrivo',
    continueWatching: 'Continua a Guardare',
    areYouStillWatching: 'Stai ancora guardando?',
    yesContinue: 'Sì, Continua',
    stopPlaying: 'Ferma',
    skipIntro: 'Salva Intro',
    skipOutro: 'Salva Finale',
    appearance: 'Aspetto',
    playback: 'Riproduzione',
    audioSubtitles: 'Audio e Sottotitoli',
    notifications: 'Notifiche',
    parentalControls: 'Controllo Genitori',
    dataUsage: 'Utilizzo Dati',
    account: 'Account',
    theme: 'Tema',
    dark: 'Scuro',
    light: 'Chiaro',
    language: 'Lingua',
    welcomeBack: 'Bentornato nel tuo universo cinematografico',
    startJourney: 'Inizia il tuo viaggio cinematografico',
    noResults: 'Nessun risultato trovato',
    loading: 'Caricamento...',
  },
  pl: {
    home: 'Strona Główna',
    movies: 'Filmy',
    tvShows: 'Seriale',
    trending: 'Popularne',
    watchlist: 'Moja Lista',
    search: 'Szukaj',
    signIn: 'Zaloguj się',
    signUp: 'Zarejestruj się',
    signOut: 'Wyloguj się',
    profile: 'Profil',
    settings: 'Ustawienia',
    watchHistory: 'Historia Oglądania',
    watchNow: 'Oglądaj Teraz',
    moreInfo: 'Więcej Informacji',
    addToWatchlist: 'Dodaj do Listy',
    removeFromWatchlist: 'Usuń z Listy',
    inWatchlist: 'Na Liście',
    back: 'Wstecz',
    save: 'Zapisz',
    cancel: 'Anuluj',
    edit: 'Edytuj',
    delete: 'Usuń',
    clear: 'Wyczyść',
    popular: 'Popularne',
    topRated: 'Najwyżej Oceniane',
    nowPlaying: 'W Kinach',
    upcoming: 'Nadchodzące',
    continueWatching: 'Kontynuuj Oglądanie',
    areYouStillWatching: 'Ciągle oglądasz?',
    yesContinue: 'Tak, Kontynuuj',
    stopPlaying: 'Zatrzymaj',
    skipIntro: 'Pomiń Intro',
    skipOutro: 'Pomiń Zakończenie',
    appearance: 'Wygląd',
    playback: 'Odtwarzanie',
    audioSubtitles: 'Audio i Napisy',
    notifications: 'Powiadomienia',
    parentalControls: 'Kontrola Rodzicielska',
    dataUsage: 'Użycie Danych',
    account: 'Konto',
    theme: 'Motyw',
    dark: 'Ciemny',
    light: 'Jasny',
    language: 'Język',
    welcomeBack: 'Witaj ponownie w swoim filmowym świecie',
    startJourney: 'Rozpocznij swoją filmową podróż',
    noResults: 'Nie znaleziono wyników',
    loading: 'Ładowanie...',
  },
  nl: {
    home: 'Home',
    movies: 'Films',
    tvShows: 'Series',
    trending: 'Trending',
    watchlist: 'Mijn Lijst',
    search: 'Zoeken',
    signIn: 'Inloggen',
    signUp: 'Registreren',
    signOut: 'Uitloggen',
    profile: 'Profiel',
    settings: 'Instellingen',
    watchHistory: 'Kijkgeschiedenis',
    watchNow: 'Nu Bekijken',
    moreInfo: 'Meer Info',
    addToWatchlist: 'Toevoegen aan Lijst',
    removeFromWatchlist: 'Verwijderen uit Lijst',
    inWatchlist: 'In Lijst',
    back: 'Terug',
    save: 'Opslaan',
    cancel: 'Annuleren',
    edit: 'Bewerken',
    delete: 'Verwijderen',
    clear: 'Wissen',
    popular: 'Populair',
    topRated: 'Best Beoordeeld',
    nowPlaying: 'In de Bioscoop',
    upcoming: 'Binnenkort',
    continueWatching: 'Verder Kijken',
    areYouStillWatching: 'Kijk je nog?',
    yesContinue: 'Ja, Doorgaan',
    stopPlaying: 'Stoppen',
    skipIntro: 'Intro Overslaan',
    skipOutro: 'Outro Overslaan',
    appearance: 'Uiterlijk',
    playback: 'Afspelen',
    audioSubtitles: 'Audio en Ondertitels',
    notifications: 'Meldingen',
    parentalControls: 'Ouderlijk Toezicht',
    dataUsage: 'Datagebruik',
    account: 'Account',
    theme: 'Thema',
    dark: 'Donker',
    light: 'Licht',
    language: 'Taal',
    welcomeBack: 'Welkom terug in je filmuniversum',
    startJourney: 'Begin je cinematografische reis',
    noResults: 'Geen resultaten gevonden',
    loading: 'Laden...',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof Translations) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const stored = localStorage.getItem('moviepopcorn_language') as Language;
    if (stored && translations[stored]) {
      setLanguageState(stored);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('moviepopcorn_language', lang);
  };

  const t = (key: keyof Translations): string => {
    return translations[language][key] || translations.en[key];
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export const languageNames: Record<Language, string> = {
  en: 'English',
  es: 'Español',
  fr: 'Français',
  de: 'Deutsch',
  zh: '中文',
  ja: '日本語',
  hi: 'हिन्दी',
  ar: 'العربية',
  pt: 'Português',
  ru: 'Русский',
  ko: '한국어',
  tr: 'Türkçe',
  it: 'Italiano',
  pl: 'Polski',
  nl: 'Nederlands',
};
